### ISSUE TITLE
Close old issues

### ISSUE THREAD

**Issue by SUPERCILEX** [the-blue-alliance/the-blue-alliance#1926]
I think it's slightly ironic that I'm creating an issue to close issues, but ok. 😆

Here were the issues I thought we could close:
- [ ] Probably irrelevant: https://github.com/the-blue-alliance/the-blue-alliance/issues/49
- [ ] Irrelevant, v3 is out: https://github.com/the-blue-alliance/the-blue-alliance/issues/79
- [ ] I doubt anyone really cares at this point: https://github.com/the-blue-alliance/the-blue-alliance/issues/87
- [ ] Probably irrelevant: https://github.com/the-blue-alliance/the-blue-alliance/issues/145
- [ ] Probably irrelevant: https://github.com/the-blue-alliance/the-blue-alliance/issues/176
- [ ] Probably irrelevant: https://github.com/the-blue-alliance/the-blue-alliance/issues/216
- [x] Probably irrelevant: https://github.com/the-blue-alliance/the-blue-alliance/issues/335
- [x] Probably irrelevant: https://github.com/the-blue-alliance/the-blue-alliance/issues/336
- [ ] I think we agreed that GameDay on mobile phones isn't useful because people are going to be at the event anyway: https://github.com/the-blue-alliance/the-blue-alliance/issues/406
- [ ] Probably irrelevant: https://github.com/the-blue-alliance/the-blue-alliance/issues/420
- [ ] Probably irrelevant: https://github.com/the-blue-alliance/the-blue-alliance/issues/552
- [x] Probably irrelevant: https://github.com/the-blue-alliance/the-blue-alliance/issues/839
- [ ] Probably irrelevant: https://github.com/the-blue-alliance/the-blue-alliance/issues/818
- [ ] Probably irrelevant: https://github.com/the-blue-alliance/the-blue-alliance/issues/779
- [ ] Probably irrelevant: https://github.com/the-blue-alliance/the-blue-alliance/issues/740
- [ ] Probably irrelevant: https://github.com/the-blue-alliance/the-blue-alliance/issues/640
- [x] Probably irrelevant: https://github.com/the-blue-alliance/the-blue-alliance/issues/638
- [x] https://github.com/the-blue-alliance/the-blue-alliance/issues/1847#issuecomment-292218503
- [x] https://github.com/the-blue-alliance/the-blue-alliance/issues/1244#issuecomment-292217756
- [x] https://github.com/the-blue-alliance/the-blue-alliance/issues/986#issuecomment-292221469
- [x] #579 - I think this is implemented
- [x] #567 - Definitely implemented
- [x] Probably irrelevant: https://github.com/the-blue-alliance/the-blue-alliance/issues/554
- [x] Probably irrelevant: https://github.com/the-blue-alliance/the-blue-alliance/issues/427
- [x] Probably irrelevant: https://github.com/the-blue-alliance/the-blue-alliance/issues/342
- [x] Probably irrelevant: https://github.com/the-blue-alliance/the-blue-alliance/issues/618
- [x] https://github.com/the-blue-alliance/the-blue-alliance/issues/67#issuecomment-292222698
- [x] https://github.com/the-blue-alliance/the-blue-alliance/issues/685#issuecomment-292223655
- [x] https://github.com/the-blue-alliance/the-blue-alliance/issues/786#issuecomment-292223425
- [x] https://github.com/the-blue-alliance/the-blue-alliance/issues/915#issuecomment-292223125
- [x] https://github.com/the-blue-alliance/the-blue-alliance/issues/921#issuecomment-292222955
- [x] https://github.com/the-blue-alliance/the-blue-alliance/issues/950#issuecomment-292221899
- [x] https://github.com/the-blue-alliance/the-blue-alliance/issues/1285#issuecomment-292217111
- [x] https://github.com/the-blue-alliance/the-blue-alliance/issues/1332#issuecomment-292216796
- [x] https://github.com/the-blue-alliance/the-blue-alliance/issues/1403#issuecomment-292215826
- [x] https://github.com/the-blue-alliance/the-blue-alliance/issues/1428#issuecomment-292224023
- [x] https://github.com/the-blue-alliance/the-blue-alliance/issues/1443#issuecomment-292215478
- [x] https://github.com/the-blue-alliance/the-blue-alliance/issues/1756#issuecomment-292214773
- [x] Probably not relevent anymore: https://github.com/the-blue-alliance/the-blue-alliance/issues/10

Does anyone want to add some more to the list?

**Comment by SUPERCILEX** [comment]
Oops, submitted eary

**Comment by dracco1993** [comment]
:shipit:

**Comment by SUPERCILEX** [comment]
@phil-lopreiato Ok, lol. I have the initial list now. 🎉 🚀

**Comment by bdaroz** [comment]
Add
#567 - Definitely implemented
#579 - I think this is implemented

Probably more to come too...

**Comment by synth3tk** [comment]
#427 - Closed
#554 - Closed
#731 - Events is paginated, but are teams? Does it even matter?

**Comment by SUPERCILEX** [comment]
@bdaroz Added yours

**Comment by BrennanB** [comment]
Isn't #1424 done as well?

**Comment by synth3tk** [comment]
It's only for Twitch chat, yes, but I guess it could be considered done. Once the FIRST webcast units go widespread, that'll make up a majority of events anyway.

**Comment by SUPERCILEX** [comment]
Closing an old issue. 😉
