### ISSUE TITLE
2018 Season Changes

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance#2056]
- [x] Team avatar from FRC API (#2061)
- [x] Ranking breakdown and ordering (#2092)
- [x] Match breakdown page (#2091)
- [x] Match table RP dots (#2091)
- [x] Additional calculations in rankings (#2092)
- [x] Additional calculations in match breakdown (FIRST added `rp`)
- [x] Verify district points (VERIFIED)
- [x] Event webcasts from FRC API (#2078)

**Comment by 770352** [comment]
I would change "Additional calculatiosn in match breakdown" to "Additional calculations in match breakdown"

**Comment by dracco1993** [comment]
FYI:
https://frcevents2.docs.apiary.io/#reference/match-results/score-details

**Comment by fangeugene** [comment]
We are good to go!
