### ISSUE TITLE
Implement 2023 season specifics

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance#5005]
See https://github.com/the-blue-alliance/the-blue-alliance/wiki/New-Season

- [x] Match breakdown #5004
- [x] Ranking sort orders #5004
- [x] Event match stats #5026
- [x] Tiebreakers #5007
- [x] Bonus RP dots #5028
- [x] Insights
- [x] Predictions
- [ ] Einstein advancement

**Comment by ZachOrr** [comment]
Do we still need Einstein advancements to be done?

**Comment by fangeugene** [comment]
> Do we still need Einstein advancements to be done?

I don't think so because it's just normal double elim not round robin. None of the tiebreaker rules change.
